[package]
name = "unruggable-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.0"
solana-client = "1.18.0"
serialport = "4.3.0"
base64 = "0.22.0"
anyhow = "1.0"
bs58 = "0.5"
bincode = "1.3.1"
